# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Search.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from UI.Watch import Ui_Form
from Controller import Controller

try:
    _fromUtf8 = QtCore.QString.fromUtf8  # @UndefinedVariable
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Search(QtGui.QWidget):
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.setupUi(self)
    def closeEvent(self,QCloseEvent):
        Controller.control.opened['dx']=0
        
        if Controller.control.opened['window']==1:
            self.window.close()
         
        return super().closeEvent(QCloseEvent)  

    def search(self):
        self.window=Ui_Form()
        self.window.listWidget.clear()
        if self.comboBox.currentIndex() ==0:
            if self.comboBook.currentIndex() ==0:
                for i in range(0,len(Controller.control.rCarte.cr)):
                    if(Controller.control.rCarte.cr[i].getIds()==int(self.lineEdit.text())):
                        self.window.update('ID : '+str(Controller.control.rCarte.cr[i].getIds()))
                        self.window.update('Title : '+str(Controller.control.rCarte.cr[i].getTitle()))
                        self.window.update('Author : '+str(Controller.control.rCarte.cr[i].getAuthor()))
                        self.window.update('------------')
            if self.comboBook.currentIndex() ==1:
                for i in range(0,len(Controller.control.rCarte.cr)):
                    if(Controller.control.rCarte.cr[i].getTitle()==self.lineEdit.text()):
                        self.window.update('ID : '+str(Controller.control.rCarte.cr[i].getIds()))
                        self.window.update('Title : '+str(Controller.control.rCarte.cr[i].getTitle()))
                        self.window.update('Author : '+str(Controller.control.rCarte.cr[i].getAuthor()))
                        self.window.update('------------')
            if self.comboBook.currentIndex() ==2:
                for i in range(0,len(Controller.control.rCarte.cr)):
                    if(Controller.control.rCarte.cr[i].getAuthor()==self.lineEdit.text()):
                        self.window.update('ID : '+str(Controller.control.rCarte.cr[i].getIds()))
                        self.window.update('Title : '+str(Controller.control.rCarte.cr[i].getTitle()))
                        self.window.update('Author : '+str(Controller.control.rCarte.cr[i].getAuthor()))
                        self.window.update('------------')
        if self.comboBox.currentIndex() ==1:
            if self.comboClient.currentIndex() ==0:
                for i in range(0,len(Controller.control.rClient.cl)):
                    if(Controller.control.rClient.cl[i].getIds()==int(self.lineEdit.text())):
                        self.window.update('ID : '+str(Controller.control.rClient.cl[i].getIds()))
                        self.window.update('Name : '+str(Controller.control.rClient.cl[i].getName()))
                        self.window.update('CNP : '+str(Controller.control.rClient.cl[i].getCnp()))
                        self.window.update('------------')
            if self.comboClient.currentIndex() ==1:
                for i in range(0,len(Controller.control.rClient.cl)):
                    if(Controller.control.rClient.cl[i].getName()==self.lineEdit.text()):
                        self.window.update('ID : '+str(Controller.control.rClient.cl[i].getIds()))
                        self.window.update('Name : '+str(Controller.control.rClient.cl[i].getName()))
                        self.window.update('CNP : '+str(Controller.control.rClient.cl[i].getCnp()))
                        self.window.update('------------')
            if self.comboClient.currentIndex() ==2:
                for i in range(0,len(Controller.control.rClient.cl)):
                    if(Controller.control.rClient.cl[i].getCnp()==self.lineEdit.text()):
                        self.window.update('ID : '+str(Controller.control.rClient.cl[i].getIds()))
                        self.window.update('Name : '+str(Controller.control.rClient.cl[i].getName()))
                        self.window.update('CNP : '+str(Controller.control.rClient.cl[i].getCnp()))
                        self.window.update('------------')
        if self.comboBox.currentIndex() ==2:
            if self.comboEntry.currentIndex() ==0:
                for i in range(0,len(Controller.control.rImprumut.im)):
                    if(Controller.control.rImprumut.im[i].getIds()==int(self.lineEdit.text())):
                        self.window.update('ID : '+str(Controller.control.rImprumut.im[i].getIds()))
                        self.window.update('ID Book : '+str(Controller.control.rImprumut.im[i].getIdb()))
                        self.window.update('ID Client : '+str(Controller.control.rImprumut.im[i].getIdc()))
                        self.window.update('Borrow Date : '+str(Controller.control.rImprumut.im[i].getDatai()))
                        self.window.update('Due Date : '+str(Controller.control.rImprumut.im[i].getDatar()))
                        self.window.update('------------')
            if self.comboEntry.currentIndex() ==1:
                for i in range(0,len(Controller.control.rImprumut.im)):
                    if(Controller.control.rImprumut.im[i].getIdb()==int(self.lineEdit.text())):
                        self.window.update('ID : '+str(Controller.control.rImprumut.im[i].getIds()))
                        self.window.update('ID Book : '+str(Controller.control.rImprumut.im[i].getIdb()))
                        self.window.update('ID Client : '+str(Controller.control.rImprumut.im[i].getIdc()))
                        self.window.update('Borrow Date : '+str(Controller.control.rImprumut.im[i].getDatai()))
                        self.window.update('Due Date : '+str(Controller.control.rImprumut.im[i].getDatar()))
                        self.window.update('------------')
            if self.comboEntry.currentIndex() ==2:
                for i in range(0,len(Controller.control.rImprumut.im)):
                    if(Controller.control.rImprumut.im[i].getIdc()==int(self.lineEdit.text())):
                        self.window.update('ID : '+str(Controller.control.rImprumut.im[i].getIds()))
                        self.window.update('ID Book : '+str(Controller.control.rImprumut.im[i].getIdb()))
                        self.window.update('ID Client : '+str(Controller.control.rImprumut.im[i].getIdc()))
                        self.window.update('Borrow Date : '+str(Controller.control.rImprumut.im[i].getDatai()))
                        self.window.update('Due Date : '+str(Controller.control.rImprumut.im[i].getDatar()))
                        self.window.update('------------')
            if self.comboEntry.currentIndex() ==3:
                for i in range(0,len(Controller.control.rImprumut.im)):
                    if(Controller.control.rImprumut.im[i].getDatai()==self.lineEdit.text()):
                        self.window.update('ID : '+str(Controller.control.rImprumut.im[i].getIds()))
                        self.window.update('ID Book : '+str(Controller.control.rImprumut.im[i].getIdb()))
                        self.window.update('ID Client : '+str(Controller.control.rImprumut.im[i].getIdc()))
                        self.window.update('Borrow Date : '+str(Controller.control.rImprumut.im[i].getDatai()))
                        self.window.update('Due Date : '+str(Controller.control.rImprumut.im[i].getDatar()))
                        self.window.update('------------')
            if self.comboEntry.currentIndex() ==4:
                for i in range(0,len(Controller.control.rImprumut.im)):
                    if(Controller.control.rImprumut.im[i].getDatar()==self.lineEdit.text()):
                        self.window.update('ID : '+str(Controller.control.rImprumut.im[i].getIds()))
                        self.window.update('ID Book : '+str(Controller.control.rImprumut.im[i].getIdb()))
                        self.window.update('ID Client : '+str(Controller.control.rImprumut.im[i].getIdc()))
                        self.window.update('Borrow Date : '+str(Controller.control.rImprumut.im[i].getDatai()))
                        self.window.update('Due Date : '+str(Controller.control.rImprumut.im[i].getDatar()))
                        self.window.update('------------')

        Controller.control.opened['window']=1   
        self.window.show()
        
    def setupUi(self, Search):
        Search.setObjectName(_fromUtf8("Search"))
        Search.resize(263, 205)
        Search.setFixedSize(263,205)
        Search.setStyleSheet(_fromUtf8("background-color: rgb(58, 58, 58);"))
        self.searchby_label = QtGui.QLabel(Search)
        self.searchby_label.setGeometry(QtCore.QRect(20, 30, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Soft Elegance"))
        font.setPointSize(16)
        self.searchby_label.setFont(font)
        self.searchby_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.searchby_label.setAlignment(QtCore.Qt.AlignCenter)
        self.searchby_label.setObjectName(_fromUtf8("searchby_label"))
        self.comboBox = QtGui.QComboBox(Search)
        self.comboBox.setGeometry(QtCore.QRect(130, 30, 121, 22))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.comboBox.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Soft Elegance"))
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.Field_label_2 = QtGui.QLabel(Search)
        self.Field_label_2.setGeometry(QtCore.QRect(20, 70, 91, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Soft Elegance"))
        font.setPointSize(16)
        self.Field_label_2.setFont(font)
        self.Field_label_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.Field_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Field_label_2.setObjectName(_fromUtf8("Field_label_2"))
        self.stackedWidget = QtGui.QStackedWidget(Search)
        self.stackedWidget.setGeometry(QtCore.QRect(110, 60, 141, 41))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.comboBook = QtGui.QComboBox(self.page)
        self.comboBook.setGeometry(QtCore.QRect(20, 10, 121, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.comboBook.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Soft Elegance"))
        font.setPointSize(11)
        self.comboBook.setFont(font)
        self.comboBook.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBook.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.comboBook.setFrame(True)
        self.comboBook.setObjectName(_fromUtf8("comboBook"))
        self.comboBook.addItem(_fromUtf8(""))
        self.comboBook.addItem(_fromUtf8(""))
        self.comboBook.addItem(_fromUtf8(""))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.comboClient = QtGui.QComboBox(self.page_2)
        self.comboClient.setGeometry(QtCore.QRect(20, 10, 121, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.comboClient.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Soft Elegance"))
        font.setPointSize(11)
        self.comboClient.setFont(font)
        self.comboClient.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboClient.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.comboClient.setFrame(True)
        self.comboClient.setObjectName(_fromUtf8("comboClient"))
        self.comboClient.addItem(_fromUtf8(""))
        self.comboClient.addItem(_fromUtf8(""))
        self.comboClient.addItem(_fromUtf8(""))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.comboEntry = QtGui.QComboBox(self.page_3)
        self.comboEntry.setGeometry(QtCore.QRect(20, 10, 121, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(58, 58, 58))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 153, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        self.comboEntry.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Soft Elegance"))
        font.setPointSize(11)
        self.comboEntry.setFont(font)
        self.comboEntry.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboEntry.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.comboEntry.setFrame(True)
        self.comboEntry.setObjectName(_fromUtf8("comboEntry"))
        self.comboEntry.addItem(_fromUtf8(""))
        self.comboEntry.addItem(_fromUtf8(""))
        self.comboEntry.addItem(_fromUtf8(""))
        self.comboEntry.addItem(_fromUtf8(""))
        self.comboEntry.addItem(_fromUtf8(""))
        self.stackedWidget.addWidget(self.page_3)
        self.lineEdit = QtGui.QLineEdit(Search)
        self.lineEdit.setGeometry(QtCore.QRect(80, 110, 113, 20))
        self.lineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.SearchButton = QtGui.QPushButton(Search)
        self.SearchButton.setGeometry(QtCore.QRect(94, 140, 81, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Soft Elegance"))
        font.setPointSize(11)
        self.SearchButton.setFont(font)
        self.SearchButton.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.SearchButton.setObjectName(_fromUtf8("SearchButton"))
        self.SearchButton.clicked.connect(self.search)
        self.retranslateUi(Search)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(Search)

    def retranslateUi(self, Search):
        Search.setWindowTitle(_translate("Search", "Search", None))
        self.searchby_label.setText(_translate("Search", "Search by ", None))
        self.comboBox.setItemText(0, _translate("Search", "Book", None))
        self.comboBox.setItemText(1, _translate("Search", "Client", None))
        self.comboBox.setItemText(2, _translate("Search", "Entry", None))
        self.Field_label_2.setText(_translate("Search", "Field", None))
        self.comboBook.setItemText(0, _translate("Search", "ID", None))
        self.comboBook.setItemText(1, _translate("Search", "Title", None))
        self.comboBook.setItemText(2, _translate("Search", "Author", None))
        self.comboClient.setItemText(0, _translate("Search", "ID", None))
        self.comboClient.setItemText(1, _translate("Search", "Name", None))
        self.comboClient.setItemText(2, _translate("Search", "CNP", None))
        self.comboEntry.setItemText(0, _translate("Search", "ID", None))
        self.comboEntry.setItemText(1, _translate("Search", "ID Book", None))
        self.comboEntry.setItemText(2, _translate("Search", "ID CLient", None))
        self.comboEntry.setItemText(3, _translate("Search", "Borrow Date", None))
        self.comboEntry.setItemText(4, _translate("Search", "Due Date", None))
        self.SearchButton.setText(_translate("Search", "SEARCH", None))

